# Generated by Django 3.2.7 on 2021-11-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
